/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_nasa_gsfc_gmsecapi_jni_gmsecJNI */

#ifndef _Included_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
#define _Included_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_initialize
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    setEnableDetach
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_setEnableDetach
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Status
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Status
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Status_Set
 * Signature: (IJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Status_1Set
  (JNIEnv *, jclass, jint, jlong, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Status_Copy
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Status_1Copy
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_Status
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1Status
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_GetString
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1GetString
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_Get
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1Get
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_GetClass
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1GetClass
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_GetCode
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1GetCode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_GetCustomCode
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1GetCustomCode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_isError
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1isError
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_IsError
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1IsError
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_SetString
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1SetString
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_SetClass
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;I)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1SetClass
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_SetCode
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;J)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1SetCode
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_SetCustomCode
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;I)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1SetCustomCode
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_Set
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;IJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1Set
  (JNIEnv *, jclass, jlong, jobject, jint, jlong, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Status_ReSet
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIStatus;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Status_1ReSet
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_ConfigFile
 * Signature: (Lgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1ConfigFile__Lgov_nasa_gsfc_gmsecapi_jni_JNIConfigFile_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_ConfigFile
 * Signature: (Lgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1ConfigFile__Lgov_nasa_gsfc_gmsecapi_jni_JNIConfigFile_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_Load
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1Load__JLgov_nasa_gsfc_gmsecapi_jni_JNIConfigFile_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_Load
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1Load__JLgov_nasa_gsfc_gmsecapi_jni_JNIConfigFile_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_Save
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1Save
  (JNIEnv *, jclass, jlong, jobject, jstring, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_ConfigFile
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1ConfigFile
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_FromXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1FromXML
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_IsLoaded
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1IsLoaded
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_LookupConfig
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1LookupConfig
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_LookupMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1LookupMessage
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_ToXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1ToXML
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_LookupSubscription
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1LookupSubscription
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_AddSubscription
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1AddSubscription
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_AddConfig
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;JLjava/lang/String;Lgov/nasa/gsfc/gmsecapi/Config;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1AddConfig
  (JNIEnv *, jclass, jlong, jobject, jlong, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_AddMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;JLjava/lang/String;Lgov/nasa/gsfc/gmsecapi/Message;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1AddMessage
  (JNIEnv *, jclass, jlong, jobject, jlong, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_AddCustomXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1AddCustomXML
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_RemoveSubscription
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1RemoveSubscription
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_RemoveConfig
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1RemoveConfig
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_RemoveMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1RemoveMessage
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConfigFile_RemoveCustomXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfigFile;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConfigFile_1RemoveCustomXML
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Config
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Config
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Config_String
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Config_1String
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Config_Copy
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Config_1Copy
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_Config
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1Config
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_AddValue
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1AddValue
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_ClearValue
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1ClearValue
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_GetValue
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Ljava/lang/String;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1GetValue
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_Clear
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1Clear
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_GetFirst
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1GetFirst
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_GetNext
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1GetNext
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_ToXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1ToXML
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Config_FromXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Config_1FromXML
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionFactory_Create
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;Lgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionFactory_1Create
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionFactory_Destroy
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionFactory_1Destroy
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionFactory_GetAPIVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionFactory_1GetAPIVersion
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_Message
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1Message
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_isValid
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1isValid
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_IsValid
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1IsValid
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_SetKind
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1SetKind
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetKind
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Lgov/nasa/gsfc/gmsecapi/GMSEC_UShort;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetKind
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_SetSubject
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1SetSubject
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetSubject
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetSubject
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_AddField
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1AddField
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetField
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetField
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetFieldCount
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Lgov/nasa/gsfc/gmsecapi/GMSEC_Long;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetFieldCount
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetFirstField
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetFirstField
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetNextField
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetNextField
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_SetConfig
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1SetConfig
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_ToXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1ToXML
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_FromXML
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1FromXML
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_ToJSON
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1ToJSON
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_FromJSON
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1FromJSON
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetTime
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetTime
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_GetMSGSize
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Lgov/nasa/gsfc/gmsecapi/GMSEC_ULong;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1GetMSGSize
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_ClearFields
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1ClearFields
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Message_ClearField
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Message_1ClearField
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_Connection
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1Connection
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Connect
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Connect
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Disconnect
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Disconnect
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Subscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Subscribe
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Subscribe_Via_Callback
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Subscribe_1Via_1Callback
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_UnSubscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1UnSubscribe
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_UnSubscribe_Via_Callback
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1UnSubscribe_1Via_1Callback
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_RegisterErrorCallback
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1RegisterErrorCallback
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_CreateMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Lgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1CreateMessage__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnection_2Lgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_CreateMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;ILgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1CreateMessage__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnection_2Ljava_lang_String_2ILgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2
  (JNIEnv *, jclass, jlong, jobject, jstring, jint, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_CreateMessageCFG
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;ILgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1CreateMessageCFG
  (JNIEnv *, jclass, jlong, jobject, jstring, jint, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_DestroyMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1DestroyMessage
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Publish
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Publish
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Request
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;ILgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Request
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Request_Via_Callback
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;ILjava/lang/Object;Z)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Request_1Via_1Callback
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jint, jobject, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_Reply
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1Reply
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_GetNextMsg
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Lgov/nasa/gsfc/gmsecapi/jni/JNIMessage;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1GetNextMsg
  (JNIEnv *, jclass, jlong, jobject, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_StartAutoDispatch
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1StartAutoDispatch
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_StopAutoDispatch
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1StopAutoDispatch
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_DispatchMsg
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1DispatchMsg
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_GetLastDispatcherStatus
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1GetLastDispatcherStatus
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_ExcludeSubject
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1ExcludeSubject
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_RemoveExcludedSubject
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1RemoveExcludedSubject
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_CloneMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Lgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1CloneMessage
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_GetLibraryRootName
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1GetLibraryRootName
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_GetLibraryVersion
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1GetLibraryVersion
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_GetPublishQueueMessageCount
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1GetPublishQueueMessageCount
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Connection_IsConnected
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnection;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Connection_1IsConnected
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Field
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Field
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueCHAR
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueCHAR
  (JNIEnv *, jclass, jlong, jobject, jstring, jbyte);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueBOOL
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueBOOL
  (JNIEnv *, jclass, jlong, jobject, jstring, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueBYTE
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueBYTE
  (JNIEnv *, jclass, jlong, jobject, jstring, jbyte);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueUBYTE
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueUBYTE
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueSHORT
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueSHORT
  (JNIEnv *, jclass, jlong, jobject, jstring, jshort);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueUSHORT
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueUSHORT
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueLONG
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueLONG
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueULONG
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueULONG
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueFLOAT
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueFLOAT
  (JNIEnv *, jclass, jlong, jobject, jstring, jfloat);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueDOUBLE
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;D)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueDOUBLE
  (JNIEnv *, jclass, jlong, jobject, jstring, jdouble);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueSTRING
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueSTRING
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueBIN
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueBIN
  (JNIEnv *, jclass, jlong, jobject, jstring, jbyteArray, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueI8
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueI8
  (JNIEnv *, jclass, jlong, jobject, jstring, jbyte);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueU8
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueU8
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueU16
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueU16
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueI16
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueI16
  (JNIEnv *, jclass, jlong, jobject, jstring, jshort);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueU32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueU32
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueI32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueI32
  (JNIEnv *, jclass, jlong, jobject, jstring, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueI64
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueI64
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueF32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueF32
  (JNIEnv *, jclass, jlong, jobject, jstring, jfloat);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetFieldValueF64
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;D)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetFieldValueF64
  (JNIEnv *, jclass, jlong, jobject, jstring, jdouble);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Field_Copy
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Field_1Copy
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_Field
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1Field
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetName
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetName
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetName
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetName
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetType
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetType
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetType
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_UShort;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetType
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueBOOL
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_Bool;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueBOOL
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueCHAR
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_Char;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueCHAR
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueSTRING
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueSTRING
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueBIN
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_Bin;Lgov/nasa/gsfc/gmsecapi/GMSEC_ULong;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueBIN
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueI8
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_I8;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueI8
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueU8
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_U8;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueU8
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueU16
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_U16;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueU16
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueI16
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_I16;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueI16
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueU32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_U32;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueU32
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueI32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_I32;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueI32
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueI64
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_I64;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueI64
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueF32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_F32;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueF32
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_GetValueF64
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Lgov/nasa/gsfc/gmsecapi/GMSEC_F64;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1GetValueF64
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueCHAR
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;B)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueCHAR
  (JNIEnv *, jclass, jlong, jobject, jbyte);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueBOOL
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Z)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueBOOL
  (JNIEnv *, jclass, jlong, jobject, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueSTRING
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueSTRING
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueBIN
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueBIN
  (JNIEnv *, jclass, jlong, jobject, jbyteArray, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueI8
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;B)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueI8
  (JNIEnv *, jclass, jlong, jobject, jbyte);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueU8
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueU8
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueU16
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueU16
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueI16
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;S)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueI16
  (JNIEnv *, jclass, jlong, jobject, jshort);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueU32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueU32
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueI32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueI32
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueI64
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;J)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueI64
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueF32
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;F)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueF32
  (JNIEnv *, jclass, jlong, jobject, jfloat);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_SetValueF64
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;D)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1SetValueF64
  (JNIEnv *, jclass, jlong, jobject, jdouble);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Field_UnSet
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Field_1UnSet
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_Log
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1Log
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_Log
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNILog;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1Log
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_SetReportingLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1SetReportingLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_GetReportingLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1GetReportingLevel
  (JNIEnv *, jclass);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_RegisterHandler
 * Signature: (Lgov/nasa/gsfc/gmsecapi/util/LogHandler;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1RegisterHandler__Lgov_nasa_gsfc_gmsecapi_util_LogHandler_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_RegisterHandler
 * Signature: (ILgov/nasa/gsfc/gmsecapi/util/LogHandler;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1RegisterHandler__ILgov_nasa_gsfc_gmsecapi_util_LogHandler_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogLevelToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogLevelToString
  (JNIEnv *, jclass, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogLevelFromString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogLevelFromString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogError
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogWarning
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogWarning
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogInfo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogVerbose
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogVerbose
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    Log_LogDebug
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_Log_1LogDebug
  (JNIEnv *, jclass, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    TimeUtil_FormatTime_s
 * Signature: (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_TimeUtil_1FormatTime_1s
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_ConnectionManager
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;IZ)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1ConnectionManager__JLgov_nasa_gsfc_gmsecapi_jni_JNIConfig_2IZ
  (JNIEnv *, jclass, jlong, jobject, jint, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    new_ConnectionManager
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_new_1ConnectionManager__JLgov_nasa_gsfc_gmsecapi_jni_JNIConfig_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    delete_ConnectionManager
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)V
 */
JNIEXPORT void JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_delete_1ConnectionManager
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_SetStandardFields
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;[J[Lgov/nasa/gsfc/gmsecapi/jni/JNIField;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1SetStandardFields
  (JNIEnv *, jclass, jlong, jobject, jlongArray, jobjectArray, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Initialize
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Initialize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Cleanup
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Cleanup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_RegisterErrorCallback
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1RegisterErrorCallback
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Subscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Subscribe__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Subscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Subscribe__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2Ljava_lang_String_2Ljava_lang_Object_2
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Subscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Subscribe__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2Ljava_lang_String_2JLgov_nasa_gsfc_gmsecapi_jni_JNIConfig_2
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_UnSubscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1UnSubscribe__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_UnSubscribe
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1UnSubscribe__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2Ljava_lang_String_2Ljava_lang_Object_2
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_CreateMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;ILgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1CreateMessage
  (JNIEnv *, jclass, jlong, jobject, jstring, jint, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ConvertMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ConvertMessage
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ConvertCleanup
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ConvertCleanup
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_CloneMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1CloneMessage
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_DestroyMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1DestroyMessage
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Publish
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Publish__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2JLgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Publish
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIConfig;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Publish__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2JLgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2JLgov_nasa_gsfc_gmsecapi_jni_JNIConfig_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Request
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;ILjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Request__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2JLgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2ILjava_lang_Object_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Request
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;ILgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Request__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2JLgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2ILgov_nasa_gsfc_gmsecapi_jni_JNIMessage_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_Reply
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1Reply
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_StartAutoDispatch
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1StartAutoDispatch
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_StopAutoDispatch
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1StopAutoDispatch__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_StopAutoDispatch
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Z)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1StopAutoDispatch__JLgov_nasa_gsfc_gmsecapi_jni_JNIConnectionManager_2Z
  (JNIEnv *, jclass, jlong, jobject, jboolean);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_GetNextMsg
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;I)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1GetNextMsg
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jint);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_DispatchMsg
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1DispatchMsg
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_GetLastDispatcherStatus
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1GetLastDispatcherStatus
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ExcludeSubject
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ExcludeSubject
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_RemoveExcludedSubject
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1RemoveExcludedSubject
  (JNIEnv *, jclass, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_GetHeartbeatMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;[J[Lgov/nasa/gsfc/gmsecapi/jni/JNIField;IJLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1GetHeartbeatMessage
  (JNIEnv *, jclass, jlong, jobject, jlongArray, jobjectArray, jint, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_StartHeartbeatService
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;[J[Lgov/nasa/gsfc/gmsecapi/jni/JNIField;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1StartHeartbeatService
  (JNIEnv *, jclass, jlong, jobject, jlongArray, jobjectArray, jint, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ChangeComponentStatus
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ChangeComponentStatus
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ChangeComponentInfo
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ChangeComponentInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ChangeCPUMemory
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ChangeCPUMemory
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_ChangeCPUUtil
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1ChangeCPUUtil
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_StopHeartbeatService
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1StopHeartbeatService
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_GetLogMessage
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;[J[Lgov/nasa/gsfc/gmsecapi/jni/JNIField;IJLgov/nasa/gsfc/gmsecapi/jni/JNIMessage;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1GetLogMessage
  (JNIEnv *, jclass, jlong, jobject, jlongArray, jobjectArray, jint, jlong, jobject, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_SetLoggingDefaults
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;[J[Lgov/nasa/gsfc/gmsecapi/jni/JNIField;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1SetLoggingDefaults
  (JNIEnv *, jclass, jlong, jobject, jlongArray, jobjectArray, jint, jstring);

/*
 * Class:     gov_nasa_gsfc_gmsecapi_jni_gmsecJNI
 * Method:    ConnectionManager_QuickLog
 * Signature: (JLgov/nasa/gsfc/gmsecapi/jni/JNIConnectionManager;Ljava/lang/String;JLgov/nasa/gsfc/gmsecapi/jni/JNIField;)J
 */
JNIEXPORT jlong JNICALL Java_gov_nasa_gsfc_gmsecapi_jni_gmsecJNI_ConnectionManager_1QuickLog
  (JNIEnv *, jclass, jlong, jobject, jstring, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
