
/*
	gmsec_version.h autogenerated on:
	07/16/2018 10:35:26
*/

#ifndef gmsec_version_h
#define gmsec_version_h

#define GMSEC_VERSION	"GMSEC API v4.4.2 [07/16/2018]"
#define GMSEC_VERSION_NUMBER "4.4.2"
#define GMSEC_API_VERSION 0x040402
#define GMSEC_OS	"Microsoft Windows [Version 10.0.17134.112]"
#define GMSEC_CXX	"Microsoft C/C++ 19.14.26430"
#define GMSEC_JAVA	"java version 10.0.1 2018-04-17"
#define GMSEC_PERL	"Perl v5.24.3, gcc, MSWin32-x64-multi-thread"


#ifdef GMSEC_OLD_MACROS

#define OS		"Microsoft Windows [Version 10.0.17134.112]"
#define JAVA_VERSION	"java version 10.0.1 2018-04-17"
#define C_PLUS_PLUS_VERSION "Microsoft C/C++ 19.14.26430"

#endif /* GMSEC_OLD_MACROS */

#endif
